package com.app.util;

public class StaticUtils {
	// columns for p_cases chain without primary key column
	public static final String PCASESCHAIN_COLS_WITHOUT_PK = " cc_caseid, cc_frombranch, cc_tobranch, cc_liaisonagentid, cc_manifestid, cc_pathid, cc_pathcost, cc_createddt, cc_createdby, cc_rtnwithliaisonagent, cc_branchpmtid, cc_branchrecievedpmt, cc_profit_pmtid, cc_qstage_tobranch, cc_qstep_tobranch, cc_qstatus_tobranch, cc_qenterdate_tobranch, cc_qaction_tobranch, cc_qactiontakenby_tobranch, cc_qstage_frombranch, cc_qstep_frombranch, cc_qstatus_frombranch, cc_qenterdate_frombranch, cc_qaction_frombranch, cc_qactiontakenby_frombranch, cc_parentchainid, cc_rtnmanifestid, cc_rtnmanifestliaison_actiontakenby, cc_liaisoncheckedbarcode, cc_liaisoncheckedby, cc_liaisoncheckeddt, cc_liaisonbar_printmanifest, cc_liaisonbarby_printmanifest, cc_liaisonbardt_printmanifest, cc_shipmentprofit";

	// columns of p_cases table without primary key column
	public static final String PCASES_COLS_WIHOUT_PK = " c_createddt, c_createdby, c_rcv_name, c_rcv_hp1, c_rcv_hp2, c_rcv_state, c_rcv_district, c_rcv_addr_rmk, c_rmk, c_receiptamt, c_receiptamt_usd, c_qty, c_shipment_cost, c_fragile, c_rural, c_sendmoney, c_assignedagent, c_custreceiptnoori, c_settled, c_pmtid, c_agentshare, c_agentsharesettled, c_agentpmtid, c_pickupagentpmtid, c_server_createddt, c_mbapp_agent_status, c_mbapp_agent_rmk, c_mbapp_agent_updatedt, c_rtnreason, c_custid, c_custhp, c_specialcase, c_pickupagent, c_paidinadvance, c_advancepmtid, c_receiptfromsystem, c_intbatchid, c_priceb4change, c_changedprice, c_changedpriceby, c_changedpriceat, c_usdpriceb4change, c_usdchangedprice, c_usdchangedpriceby, c_usdchangedpriceat, c_productinfo, c_products, c_receivedfrom_system, c_receivedfrom_caseid, c_sentto_system, c_sentto_caseid, c_int_batchid, c_branchcode, c_partial_return, c_partial_qtyrtn, c_agentpartial_returnedid, c_dlvagent_manifestid, c_lastchainid, q_code, q_stage, q_step, q_status, q_enterdate, q_rank, q_action, q_action_datetime, q_action_takenby, q_previous_qcode, q_previous_action, q_previous_action_taken_by, q_assigned_to, q_manifest_id, q_branch, q_comingfrombranch, q_postopnedto, q_postponedoption, q_rmk, q_previous_rmk, c_allowrtncustomer, c_allowrtnagent, c_allowcustpay, c_allowbranchpay, c_alllowagentpay, c_cust_rtnid, c_pickupagent_rtnid, c_mastercustid, c_mastercusthp, c_creationstartpoint, c_billprinted, c_printedby, c_printedat, c_dategiventodlvagent, c_agentrtnid, c_agentcheckedbarcode, c_agentbarcodecheckedby, c_agentbarcodecheckeddt, c_shipmentprofit, c_starredbydlvagent, c_starreddt, c_starredbycustomer, c_starredbycustomerdt, c_customerstarcreatedby, c_pickupmanifest, c_paytodlvcheck, c_paytodlvcheckby, c_paytodlvcheckdt, c_custhandle, c_handletype, c_handlermk, c_handlecreatedby, c_handlecreateddt, c_latest_ticketid, c_changed_receiptprice_after_dlv, c_followupby, c_started_followup_at, c_provided_followup, c_created_date_only, c_pickup_share, c_pickup_share_pmtid, c_confirm_rtn_district_change, c_branch_confirm_rtn_state_change, c_must_confirm_usd_change, c_confirmed_usd_change, c_confirmed_usd_change_by, c_excelnumber, c_paid_delivery_cost_in_advance, c_parentid, c_seperated, c_parent_of, c_deletedby, c_deleteddt";

	public static final String PCASES_COLS = "c_id, c_createddt, c_createdby, c_rcv_name, c_rcv_hp1, c_rcv_hp2, c_rcv_state, c_rcv_district, c_rcv_addr_rmk, c_rmk, c_receiptamt, c_receiptamt_usd, c_qty, c_shipment_cost, c_fragile, c_rural, c_sendmoney, c_assignedagent, c_custreceiptnoori, c_settled, c_pmtid, c_agentshare, c_agentsharesettled, c_agentpmtid, c_pickupagentpmtid, c_server_createddt, c_mbapp_agent_status, c_mbapp_agent_rmk, c_mbapp_agent_updatedt, c_rtnreason, c_custid, c_custhp, c_specialcase, c_pickupagent, c_paidinadvance, c_advancepmtid, c_receiptfromsystem, c_intbatchid, c_priceb4change, c_changedprice, c_changedpriceby, c_changedpriceat, c_usdpriceb4change, c_usdchangedprice, c_usdchangedpriceby, c_usdchangedpriceat, c_productinfo, c_products, c_receivedfrom_system, c_receivedfrom_caseid, c_sentto_system, c_sentto_caseid, c_int_batchid, c_branchcode, c_partial_return, c_partial_qtyrtn, c_agentpartial_returnedid, c_dlvagent_manifestid, c_lastchainid, q_code, q_stage, q_step, q_status, q_enterdate, q_rank, q_action, q_action_datetime, q_action_takenby, q_previous_qcode, q_previous_action, q_previous_action_taken_by, q_assigned_to, q_manifest_id, q_branch, q_comingfrombranch, q_postopnedto, q_postponedoption, q_rmk, q_previous_rmk, c_allowrtncustomer, c_allowrtnagent, c_allowcustpay, c_allowbranchpay, c_alllowagentpay, c_cust_rtnid, c_pickupagent_rtnid, c_mastercustid, c_mastercusthp, c_creationstartpoint, c_billprinted, c_printedby, c_printedat, c_dategiventodlvagent, c_agentrtnid, c_agentcheckedbarcode, c_agentbarcodecheckedby, c_agentbarcodecheckeddt, c_shipmentprofit, c_starredbydlvagent, c_starreddt, c_starredbycustomer, c_starredbycustomerdt, c_customerstarcreatedby, c_pickupmanifest, c_paytodlvcheck, c_paytodlvcheckby, c_paytodlvcheckdt, c_custhandle, c_handletype, c_handlermk, c_handlecreatedby, c_handlecreateddt, c_latest_ticketid, c_changed_receiptprice_after_dlv, c_followupby, c_started_followup_at, c_provided_followup, c_created_date_only, c_pickup_share, c_pickup_share_pmtid, c_confirm_rtn_district_change, c_branch_confirm_rtn_state_change, c_must_confirm_usd_change, c_confirmed_usd_change, c_confirmed_usd_change_by, c_excelnumber, c_paid_delivery_cost_in_advance, c_parentid, c_seperated, c_parent_of, c_deletedby, c_deleteddt";
}
