package com.app.financials;

public enum FinOperationCode {
	CASES,
	GIVEDEBT,
	DEBT_SETTLE,
	GIVEMONEY_NODEBT,
	CUSTOMER_CREDIT,
	COMPANY_CREDIT,
	RCV_MONEY_NOCREDIT,
	REG_DEBT,
	EXPENSES,
	SHARE,
	LIAISON_SHARE_OUT_BOUND_CASES,
	ERROR,
	ASSIGNDEBT
}
